
## ParseIntPipe Error
curl http://localhost:3000/users/userId

###
curl http://localhost:3000/users/b00d6a41-1e20-11ee-9f03-af8ab101581d \
 -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBiMDI1M2MxLTFlMjEtMTFlZS04YjJmLTNmYmFmMTExNzEyNiIsIm5hbWUiOiJ3b255b25nLnl1biIsImVtYWlsIjoieXd5aTE5OTJAZ21haWwuY29tIiwiaWF0IjoxNjg5NTA5Njk3LCJleHAiOjE2ODk1OTYwOTcsImF1ZCI6ImxvY2FsaG9zdCIsImlzcyI6Im5lc3RqcyBsZWFybmluZyJ9.qXiuT-Zr9lwu0J_Opssr_4h72Q9e4RC1hxpc_unLysU'

